version: '4.19.0'

services:

  backend:
    build: 
      context: ./backendAPI
      dockerfile: Dockerfile
      args:
        - APP_ENV=local
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ./backendAPI:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=exetel
      - MYSQL_USER=exetel_user
      - MYSQL_PASSWORD=exetel_root
      - MYSQL_ROOT_PASSWORD=exetel_root
    volumes:
      - exetel-vol:/var/lib/mysql

volumes:
  exetel-vol: ~